# compose.yaml

services:
  php:
    image: ${IMAGES_PREFIX:-}-app-php
    container_name: ${IMAGES_PREFIX:-}-php-app # You can change this name if needed
    restart: unless-stopped
    build:
      context: .
      target: frankenphp_prod # Use the prod stage for default
    # FIX: Explicitly set the command to run the Caddy server binary, 
    # resolving the "docker-entrypoint: executable file not found" error.
    command: ["/usr/bin/caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      # Use the mysql connection defined in the environment variables
      DATABASE_URL: mysql://${MYSQL_USER:-app}:${MYSQL_PASSWORD:-!ChangeMe!}@database:3306/${MYSQL_DATABASE:-app}?serverVersion=${MYSQL_VERSION:-8}&charset=${MYSQL_CHARSET:-utf8mb4}
      # Run "composer require symfony/mercure-bundle" to install and configure the Mercure integration
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://php/.well-known/mercure}
      MERCURE_PUBLIC_URL: ${CADDY_MERCURE_PUBLIC_URL:-https://${SERVER_NAME:-localhost}:${HTTPS_PORT:-443}/.well-known/mercure}
       # The two next lines can be removed after initial installation
      SYMFONY_VERSION: ${SYMFONY_VERSION:-}
      STABILITY: ${STABILITY:-stable}
    depends_on:
      - database
    labels:
      caddy: ${SERVER_NAME:-localhost}
      caddy.mercure: ${CADDY_MERCURE_JWT_KEY:-!ChangeThisMercureHubJWTSecretKey!}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: udp
      - "54112:54112"
  database:
    image: mysql:${MYSQL_VERSION:-8}
    # NOTE: The setup script will replace this ports line with the user-defined host port: ${DB_HOST_PORT}:3306
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-} # Root password
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-} # App user password
      MYSQL_USER: ${MYSQL_USER:-} # App user
      MYSQL_CHARSET: ${MYSQL_CHARSET:-utf8mb4}
    volumes:
      # The setup script add a prefix to 'database_volume'
      - database_volume:/var/lib/mysql

volumes:
  database_volume: # The setup script add a prefix to 'database_volume'
  caddy_data:
  caddy_config: