# compose.yaml

services:
  php:
    image: ${IMAGES_PREFIX:-}app-php
    container_name: php-app # You can change this name if needed
    restart: unless-stopped
    build:
      context: .
      target: frankenphp_prod # Use the prod stage for default
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      # Use the mysql connection defined in the environment variables
      DATABASE_URL: mysql://${MYSQL_USER:-app}:${MYSQL_PASSWORD:-!ChangeMe!}@database:3306/${MYSQL_DATABASE:-app}?serverVersion=${MYSQL_VERSION:-8}&charset=${MYSQL_CHARSET:-utf8mb4}
      # Run "composer require symfony/mercure-bundle" to install and configure the Mercure integration
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://php/.well-known/mercure}
      MERCURE_PUBLIC_URL: ${CADDY_MERCURE_PUBLIC_URL:-https://${SERVER_NAME:-localhost}:${HTTPS_PORT:-443}/.well-known/mercure}
    depends_on:
      - database
    labels:
      caddy: ${SERVER_NAME:-localhost}
      caddy.mercure: ${CADDY_MERCURE_JWT_KEY:-!ChangeThisMercureHubJWTSecretKey!}

  database:
    image: mysql:${MYSQL_VERSION:-8}
    # The setup script will replace this ports line with the user-defined host port: ${DB_HOST_PORT}:3306
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-} # Root password
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-} # App user password
      MYSQL_USER: ${MYSQL_USER:-} # App user
      MYSQL_CHARSET: ${MYSQL_CHARSET:-utf8mb4}
    volumes:
      # The setup script will replace 'machinistmate_volume' with a unique name
      - machinistmate_volume:/var/lib/mysql

volumes:
  machinistmate_volume: # The setup script will replace this volume name with a unique name